inscripciones/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('inscripciones_form/<int:pk>/', views.inscripciones_form, name='inscripciones_form'),
    path('lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
    path('eliminar_inscripcion/<int:id>/', views.eliminar_inscripcion, name= 'eliminar_inscripcion'),
    path('editar_inscripcion/<int:id>/', views.editar_inscripcion, name= 'editar_inscripcion'),
]   

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('registro/', views.registro, name="registro"),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name='login'),
    path('crear_curso/', views.crear_curso, name='crear_curso'),
    path('eliminarCurso/<int:id>/', views.eliminarCurso, name= 'eliminarCurso'),
    path('editarCurso/<int:id>/', views.editarCurso, name='editarCurso'),
    path('lista_form/', views.lista_form, name='lista_form'),
    path('inscritos_curso/<int:id>/', views.inscritosCurso, name="inscritos_curso"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls','main'), namespace='main')),
    path('inscripciones/', include(('inscripciones.urls','inscripciones'), namespace='inscripciones'))
]

main/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Curso(models.Model):

    curso_titulo= models.CharField(max_length=200)
    curso_contenido= models.TextField()
    curso_publicado= models.DateTimeField("fecha de publicacion", default=datetime.now())
    costo = models.DecimalField(max_digits=5, decimal_places=2, default=0)


    def __str__(self):
        return self.curso_titulo

main/forms.py
from django import forms

from .models import *

class CursoForm(forms.ModelForm):
    class Meta:
        
        model = Curso 
        fields = '__all__'

main/views.py
from main.forms import CursoForm
import main
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm 
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.db.models import Sum, Count
from inscripciones.models import*
from .models import Curso
  
# Create your views here.

def homepage(request):
    return render(request, "main/inicio.html", {"cursos": Curso.objects.all})

def registro(request):

    if request.method =="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save()
            nombre_usuario = form.cleaned_data.get('username')
            messages.success(request, f"Nueva Cuenta Creada : {nombre_usuario}")
            login(request, usuario)
            messages.info(request, f"Has sido logeado")
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = UserCreationForm 
    return render(request, "main/registro.html", {"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Saliste exitosamente")
    return redirect("main:homepage")

def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contraseña = form.cleaned_data.get('password')
            user = authenticate(username = usuario, password = contraseña)

            if user is not None:
                login(request, user)
                messages.info(request, f"Estas logeado como {usuario}")
                return redirect("main:homepage")
            else:
                messages.info(request, f"Usuario o contraseña incorrecta")
        else:
            messages.info(request, f"Usuario o contraseña incorrecta")

    form = AuthenticationForm()
    return render(request, "main/login.html", {"form": form})

def crear_curso(request):
    form = CursoForm() 
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:lista_form')
        else: 
            context = {
                'forms': form
            }
            return redirect(request, "main/curso_forms.html", context)
    context = {
        'forms': form
    }
    return render(request, "main/curso_forms.html", context)


def lista_form(request):
    cursos = Curso.objects.all()
    context = {
        'cursos':cursos
    }
    return render(request, "main/listas.html", context)


def eliminarCurso(request,id):
    curso = Curso.objects.get(id = id)
    curso.delete()
    return redirect('main:lista_form')


def editarCurso(request,id):
    curso = Curso.objects.get(id = id)
    print(curso)
    form = CursoForm(instance = curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance= curso)
        if form.is_valid():
            form.save()
            messages.info(request, f"Curso editado correctamente")
            return redirect('main:lista_form')
    contexto = {
            'form': form
        }
    return render(request, "main/agregar.html", contexto)


def inscritosCurso(request, id):
    cursos = Curso.objects.get(id=id)
    inscritos_curso = Inscripcion.objects.filter(curso = cursos)
    suma_edad = inscritos_curso.aggregate(Sum('edad'))
    div_edad = inscritos_curso.aggregate(Count('edad'))
    print(suma_edad)
    print(div_edad)
    contexto = {
        'cursos': cursos,
        'inscritos_curso': inscritos_curso, 
        'suma_edad': suma_edad,
        'div_edad' : div_edad,
    }
    return render(request, 'inscripciones/lista_inscritos.html', contexto)

main/templates/main/agregar.html
{% extends 'main/principal.html' %}
{% block titulo %} Inscripcion de Estudiantes {% endblock titulo%}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<center>
  <h2>Registrar un nuevo Curso</h2>

</center>
<form method="post">
{% csrf_token %}
{{form.as_p}}


<center><button class="btn btn-success" type="submit">Editar</button></center>

</form>

{% endblock content %}

main/templates/main/curso_forms.html
{% extends "main/principal.html" %} 
{% load bootstrap4 %}

{% block content %}   

<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<form action="" method="POST">
    {% csrf_token %} 
    {% bootstrap_form forms %}
    <button class="btn btn-success" type="submit">Crear</button>
</form>

{% endblock %}

main/templates/main/inicio.html
{% extends "main/principal.html" %} 
{% block content %}    
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <div class="container">
        <div class="row">

            {% for cur in cursos %} 
            <div class="col s12 m6">

                <div class="card blue-grey darken-1">

                    <div class="card-content white-text">
                    <span class="card-title">{{cur.curso_titulo}}</span>
                    <p>{{cur.curso_contenido|safe}}</p>
                    <p>{{cur.curso_publicado|date:"l d F Y"}}</p>
                    </div>
                    <div class="card-action">
                    <a href="#">Ir al Curso</a>
                    <a href="{% url 'inscripciones:inscripciones_form' cur.pk %}">Inscripciones</a>
                    <a href="{% url 'main:inscritos_curso' cur.pk %}">Inscritos</a>
                    </div>
                </div>        
            </div>
            
            {% endfor %}
        </div>
    </div>


{% endblock content%}

main/templates/main/listas.html
{% extends "main/principal.html" %}
{% block titulo %} Lista de Cursos {% endblock titulo%}


{% block  js %}
    <script>
        function eliminarCurso(id){
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                if (result.isConfirmed) {
                    Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
            }
            })
        }
    </script>
{% endblock  %}




{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

{{block.super}}
<center><h1>Lista de Cursos</h1></center>

<table class="table table-bordered">
    <thead>
        <tr class="text-center">    
            <th>Título</th>    
            <th>Contenido</th>    
            <th>Fecha Publicada</th> 
            <th>Costo</th>
            <th>Acciones</th>      
        </tr>
    </thead>

    <tbody>
        {% for cur in cursos %}
        <tr class="text-center">    
            <td>{{cur.curso_titulo}}</td>    
            <td class="text-center">{{cur.curso_contenido}}</td>    
            <td class="text-center">{{cur.curso_publicado}}</td>
            <td class="text-center">{{cur.costo}}</td>
            <td class="text-center"><a href="{% url 'main:editarCurso' cur.id %}" class="btn btn-info btn-sm">Editar</a> |
            <a href="{% url 'main:eliminarCurso' cur.id %}" class="btn btn-danger">Eliminar</a></td> 
        </tr>
        {% endfor %}

    </tbody>


</table>



{% endblock content %}


<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

main/templates/main/login.html
{% extends "main/principal.html" %} 
{% load bootstrap4 %}
{% block content %}   

<form action="" method="POST">
    {% csrf_token %} 
    {% bootstrap_form form %}
    <button class="btn btn-success" type="submit">Entrar</button>
</form>

Si aun no tienes una cuenta, ve a <a class="btn btn-success" href="#">Registro</a>


{% endblock %}

main/templates/main/principal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>Document</title>

    {% include "main/includes/navbar.html" %}
    
</head>
<body>

    

<div class="container">
    <br>
      {% block content %} {% endblock %}
</div>
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    

       {% if messages %}
            {% for message in messages %}
                <!-- Mesaje de success -->
                {% if message.tags == 'success' %}
                    <script>
                        M.toast({
                        html: '{{message}}', 
                        classes: 'green rounded', 
                        displayLength: 2000,
                    })
                    </script>

                {% endif %} 
                
                <!-- Mesaje de info -->
                {% if message.tags == 'info' %}
                    <script>
                        M.toast({html: '{{message}}', 
                        classes: 'blue rounded', 
                        displayLength: 2000,
                    })
                    </script>

                {% endif %} 

                <!-- Mesaje de peligro -->
                {% if message.tags == 'warning' %}
                    <script>
                        M.toast({html: '{{message}}',
                        clasesesgth: 'yellow rounded',
                        displayLength: 2000,
                    })
                    </script>

                {% endif %} 

                <!-- Mesaje de error -->
                {% if message.tags == 'error' %}
                    <script>
                        M.toast({html: '{{message}}', 
                        classes: 'red rounded', 
                        displayLength: 2000,
                    })
                    </script>

                {% endif %} 
            {% endfor %}
        {% endif %}
   

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    

    </body>
</html>

main/templates/main/registro.html
{% extends "main/principal.html" %} 
{% block content %}   
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<form action="" method="POST">
    {% csrf_token %} 
    {{form.as_p}}
    <button class="btn btn-success" type="submit">Registrar</button>
</form>

Si ya tienes una cuente, ve a <a class="btn btn-outline-success" href="main:homepage">Entrar</a>


{% endblock content%}