inscripciones/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('inscripciones_form/<int:pk>/', views.inscripciones_form, name='inscripciones_form'),
    path('lista_estudiantes/', views.lista_estudiantes, name='lista_estudiantes'),
    path('eliminar_inscripcion/<int:id>/', views.eliminar_inscripcion, name= 'eliminar_inscripcion'),
    path('editar_inscripcion/<int:id>/', views.editar_inscripcion, name= 'editar_inscripcion'),
]   

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('registro/', views.registro, name="registro"),
    path('logout/', views.logout_request, name="logout"),
    path('login/', views.login_request, name='login'),
    path('crear_curso/', views.crear_curso, name='crear_curso'),
    path('eliminarCurso/<int:id>/', views.eliminarCurso, name= 'eliminarCurso'),
    path('editarCurso/<int:id>/', views.editarCurso, name='editarCurso'),
    path('lista_form/', views.lista_form, name='lista_form'),
    path('inscritos_curso/<int:id>/', views.inscritosCurso, name="inscritos_curso"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls','main'), namespace='main')),
    path('inscripciones/', include(('inscripciones.urls','inscripciones'), namespace='inscripciones'))
]

inscripciones/models.py
from main.models import Curso
from django.contrib.auth.models import User
from django.db import models
from django.db.models.fields import DateTimeField
from datetime import datetime

# Create your models here.

class Inscripcion(models.Model):
    estudiante = models.ForeignKey(User, on_delete=models.CASCADE)
    Nombres = models.CharField(max_length=100)
    Apellidos= models.CharField(max_length=100)
    edad = models.IntegerField()
    fecha_inscripcion = models.DateTimeField("fecha de inscripcion", default=datetime.now())
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    costo_total = models.DecimalField(max_digits=5, decimal_places=2)
    
    def _str_(self):
        return '%s %s' % (self.estudiante, self.fecha_inscripcion, self.curso, self.costo_total)

main/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Curso(models.Model):

    curso_titulo= models.CharField(max_length=200)
    curso_contenido= models.TextField()
    curso_publicado= models.DateTimeField("fecha de publicacion", default=datetime.now())
    costo = models.DecimalField(max_digits=5, decimal_places=2, default=0)


    def __str__(self):
        return self.curso_titulo

main/forms.py
from django import forms

from .models import *

class CursoForm(forms.ModelForm):
    class Meta:
        
        model = Curso 
        fields = '__all__'

inscripciones/views.py
from django.db.models.aggregates import Count
from inscripciones.form import EstudianteForm, InscripcionForm, RegistroForm
from sys import prefix
from .models import Inscripcion
from django.shortcuts import redirect, render
from django.contrib import messages
from main.models import Curso
from django.db.models import Sum



# Create your views here.
#Para guardar las inscripciones
def inscripciones_form(request, pk):
    print('Registro de Inscripciones')
    registro_form = RegistroForm(prefix='form_registro')
    inscripcion_form = InscripcionForm(prefix='form inscripcion')

    contexto = {
        'registro_form' : registro_form,
        'inscripcion_form' : inscripcion_form
    }
    if request.method == 'POST':
        registro_form = RegistroForm(request.POST, prefix='form_registro')
        inscripcion_form = InscripcionForm(request.POST, prefix='form inscripcion')

        if registro_form.is_valid() and inscripcion_form.is_valid():
            estudiante = registro_form.save(commit=False)
            print('giuardo aki1')
            estudiante.user = request.user
            estudiante.save()
            curso = Curso.objects.get(pk = pk)
            print('2')
            inscripcion = inscripcion_form.save(commit=False)
            inscripcion.curso = curso
            inscripcion.estudiante = estudiante
            inscripcion.save()
            return redirect('inscripciones:lista_estudiantes')
        else: 
            print('ERRORR')
            print(inscripcion_form.errors)
            messages.error(request, registro_form.errors)
            messages.error(request, inscripcion_form.errors)
    return render(request, 'inscripciones/inscripcion_form.html', contexto)


#para mostrar la lista de inscripciones
def lista_estudiantes(request):
    inscritos_curso = Inscripcion.objects.all()
    suma_edad = inscritos_curso.aggregate(Sum('edad'))
    div_edad = inscritos_curso.aggregate(Count('edad'))
    contexto = {
        'inscritos_curso':inscritos_curso,
        'suma_edad': suma_edad,
        'div_edad' : div_edad,
    }
    return render(request, "inscripciones/lista_inscritos.html", contexto)


#eliminar estudiantes
def eliminar_inscripcion(request,id):
    inscripcion = Inscripcion.objects.get(id = id)
    inscripcion.delete()
    return redirect('inscripciones:lista_estudiantes')  

#editar estudiantes 
def editar_inscripcion(request, id):
    inscripcion = Inscripcion.objects.get(id = id)
    user = inscripcion.estudiante
    if request.method == 'GET':
        estudiante_form = EstudianteForm(instance=user)
        inscripcion_form = InscripcionForm(instance=inscripcion) 
        contexto = {
        'estudiante_form':estudiante_form,
        'inscripcion_form':inscripcion_form

        }
    else:
        estudiante_form = EstudianteForm(request.POST, instance=user)
        inscripcion_form = InscripcionForm(request.POST, instance=inscripcion) 
        contexto = {
        'estudiante_form':estudiante_form,
        'inscripcion_form':inscripcion_form

        }
        if estudiante_form.is_valid() and inscripcion_form.is_valid():
            estudiante = estudiante_form.save(commit=False)
            estudiante.user = request.user
            estudiante.save()
            
            inscripcion = inscripcion_form.save(commit=False)
            inscripcion.estudiante = estudiante
            inscripcion.save()
            return redirect('inscripciones:lista_estudiantes')

        else:
            print('Error en los forms')
            print(inscripcion_form.errors)
            messages.error(request, estudiante_form.errors)
            messages.error(request, inscripcion_form.errors)
    return render(request,'inscripciones/editar_form.html', contexto)

main/views.py
from main.forms import CursoForm
import main
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm 
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.db.models import Sum, Count
from inscripciones.models import*
from .models import Curso
  
# Create your views here.

def homepage(request):
    return render(request, "main/inicio.html", {"cursos": Curso.objects.all})

def registro(request):

    if request.method =="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            usuario = form.save()
            nombre_usuario = form.cleaned_data.get('username')
            messages.success(request, f"Nueva Cuenta Creada : {nombre_usuario}")
            login(request, usuario)
            messages.info(request, f"Has sido logeado")
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = UserCreationForm 
    return render(request, "main/registro.html", {"form":form})


def logout_request(request):
    logout(request)
    messages.info(request, "Saliste exitosamente")
    return redirect("main:homepage")

def login_request(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contraseña = form.cleaned_data.get('password')
            user = authenticate(username = usuario, password = contraseña)

            if user is not None:
                login(request, user)
                messages.info(request, f"Estas logeado como {usuario}")
                return redirect("main:homepage")
            else:
                messages.info(request, f"Usuario o contraseña incorrecta")
        else:
            messages.info(request, f"Usuario o contraseña incorrecta")

    form = AuthenticationForm()
    return render(request, "main/login.html", {"form": form})

def crear_curso(request):
    form = CursoForm() 
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:lista_form')
        else: 
            context = {
                'forms': form
            }
            return redirect(request, "main/curso_forms.html", context)
    context = {
        'forms': form
    }
    return render(request, "main/curso_forms.html", context)


def lista_form(request):
    cursos = Curso.objects.all()
    context = {
        'cursos':cursos
    }
    return render(request, "main/listas.html", context)


def eliminarCurso(request,id):
    curso = Curso.objects.get(id = id)
    curso.delete()
    return redirect('main:lista_form')


def editarCurso(request,id):
    curso = Curso.objects.get(id = id)
    print(curso)
    form = CursoForm(instance = curso)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance= curso)
        if form.is_valid():
            form.save()
            messages.info(request, f"Curso editado correctamente")
            return redirect('main:lista_form')
    contexto = {
            'form': form
        }
    return render(request, "main/agregar.html", contexto)


def inscritosCurso(request, id):
    cursos = Curso.objects.get(id=id)
    inscritos_curso = Inscripcion.objects.filter(curso = cursos)
    suma_edad = inscritos_curso.aggregate(Sum('edad'))
    div_edad = inscritos_curso.aggregate(Count('edad'))
    print(suma_edad)
    print(div_edad)
    contexto = {
        'cursos': cursos,
        'inscritos_curso': inscritos_curso, 
        'suma_edad': suma_edad,
        'div_edad' : div_edad,
    }
    return render(request, 'inscripciones/lista_inscritos.html', contexto)

main/templates/inscripciones/editar_form.html
{% extends 'main/principal.html' %}
{% block titulo %} Inscripcion de Estudiantes {% endblock titulo%}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<center><h2>Formulario de Registro</h2></center><br>

<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Import: {% endif %}
            {{ message }}

        </li>
        {% endfor%}
    </ul>
    {% endif %}
</div>

<form method="post">
    {% csrf_token %}
    {{estudiante_form.as_p}}
    {{inscripcion_form.as_p}}<br>
    
    
    
    <center><button class="btn btn-success" type="submit">Editar</button></center>

 </form>

{% endblock content %}

main/templates/inscripciones/inscripcion_form.html
{% extends 'main/principal.html' %}
{% block titulo %} Inscripcion de Estudiantes {% endblock titulo%}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<center><h2>Formulario de Registro</h2></center><br>

<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Import: {% endif %}
            {{ message }}

        </li>
        {% endfor%}
    </ul>
    {% endif %}
</div>

<form action="" method="POST">
    {% csrf_token %}
    {{registro_form.as_p}}
    {{inscripcion_form.as_p}}<br>
    
    
    
    <center><button class="btn btn-primary btn-block" type="submit">Crear</button></center>

 </form>

{% endblock content %}

main/templates/inscripciones/lista_inscritos.html
{% extends 'main/principal.html' %}
{% block titulo %} Inscripcion de Estudiantes {% endblock titulo%}

{% block content %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

<center><h3 id="tittle_pagina">Lista de Estudiantes Registrados {{ cursos }} </h3></center>

<div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{message.tags}}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Import: {% endif %}
            {{ message }}

        </li>
        {% endfor%}
    </ul>
    {% endif %}
</div>

<table class="table table-bordered">
    <thead>
        <tr class="text-center">    
            <th>Estudiante</th>
            <th>Edad</th>   
            <th>Fecha de Inscripcion</th>    
            <th>Curso Inscrito</th>    
            <th>Precio</th>    
            <th>Opciones</th>    
        </tr>
    </thead>

    <tbody>
        {% for est in inscritos_curso %}
        <tr class="text-center">    
            <td>{{est.Nombres}} {{est.Apellidos}}</td> 
            <td class="edad_promedio text-center">{{est.edad}}</td>       
            <td class="text-center">{{est.fecha_inscripcion}}</td>    
            <td class="text-center">{{est.curso}}</td>
            <td class="fila_costo text-center">{{est.costo_total}}</td>
            <td class="text-center"><a href="{% url 'inscripciones:editar_inscripcion' est.id %}" class="btn btn-info">Editar</a> |
            <a href="{% url 'inscripciones:eliminar_inscripcion' est.id %}" class="btn btn-danger">Eliminar</a></td>
        </tr>
        {% endfor %}

    </tbody>


</table>

<h7>Total Recaudado: <span id="totaljs"></span></h7><br>
<h7>Edad Promedio Frond: <span id="totaldeEdad"></span> Años</h7>
<h4>Edad Promedio Back: {% widthratio suma_edad.edad__sum div_edad.edad__count 1 %} años</h4>


<script>
var suma_costos = document.querySelectorAll(".fila_costo");
    var total = 0;
    suma_costos.forEach(function (e) {
        var suma = parseFloat(e.textContent);
        total += suma;
    });
    var suma = document.querySelectorAll("#totaljs");
    suma[0].innerHTML =total.toFixed(2)

</script>
<!--Sirve para calcular la media de edades de los Estudiante-->    
<script>
    var sumaFilas = document.querySelectorAll(".edad_promedio");
    var total = 0;
    var con = 0;
    
    sumaFilas.forEach(function(e){

        var suma = parseFloat(e.textContent);
        total += suma;
        console.log(total);
        console.log(sumaFilas.length)
    });

    resultado = (total/sumaFilas.length)
    console.log(resultado)
    var suma = document.querySelectorAll("#totaldeEdad");
    suma[0].innerHTML = resultado.toFixed(1)
</script>

{% endblock content %}